FORMAT: 1A
HOST: https://dev.api.privetapp.ru/ar/v1/

# Privet AR

## Общее
- Все запросы должны идти через **HTTPS**
- Все данные отправляемые и получаемые имеют формат **JSON**, кроме GET/DELETE запросов, они отправляются как **URL Parameters**
- Тело ответа передается с `Content-Type: application/json`

## Аутентификация
Все запросы передаются с параметром сессии `sessionId`, полученной от приложения. Если сессия устарела, сервер возвращает объект `error` с HTTP статус кодом `401`

## Используемые методы
- **GET** — Получение ресурса или коллекции
- **POST** — Создание ресурса
- **PUT** — Модификация ресурса
- **DELETE** — Удаление ресурса

## Используемые коды состояния
### Успех
- **200 Success** — Все хорошо
- **201 Created** — Ресурс создан, в ответ на **POST**, в теле ответа содержится объект ресурса
- **204 No Content** — Не нужен ресурс в Body, например успешные операции **DELETE**

### Перенаправление
- **304 Not Modified** — Неуспешная операция PUT

### Ошибка клиента
- **401 Unauthorized** — Сессия устарела, необходимо разлогиниться
- **403 Forbidden** — Запрещено делать запрос в данный момент, например попытка назначить встречу при уже активной
- **404 Not Found** — Ресурс не найден, при обращении клиента к несуществующему адресу ресурса, например попытка получить по ID уже удаленную встречу
- **409 Conflict** — Состояние ресурса изменилось пока совершался запрос, например попытка подтвердить встречу отмененную другой стороной

### Ошибка сервера
- **500 Internal Server Error** — Внутренняя ошибка сервера
- **501 Not Implemented** — Такого метода не существует, на любой не описанный здесь запрос

## Ошибки
Ошибки отправляются на любой не `2xx` код состояния с объектом `error` в теле ответа

|         |             |                Пример                |    Тип     |Обязательный|               Описание               |
|---------|-------------|--------------------------------------|------------|:----------:|--------------------------------------|
|**error**|             |                                      |            |   **+**    |      Объект ошибки с описанием       |
|         |  *message*  |"Вы не можете назначить новую встречу"|  `string`  |   **+**    |          Короткий копирайт           |
|         |*description*|    "Отмените предыдущую встречу"     |  `string`  |   **-**    |         Развернутый копирайт         |

## Время
Везде где передается время — формат **ISO 8601** `YYYY-MM-DDTHH:MM:SSZ`.


# Radar [/targets]

Метод отдает запрашиваемое количество людей в радиусе 360 градусов с равномерным распределением по градусам, и запасом для обновления.

При старте приложение делает запрос на этот метод. Последующие запросы делаются при нажатии на кнопку обновления.

## Targets [GET]

Параметры запроса:
+ `sessionId` : `653527D9-D4E8-43D7-A8C1-5B28C04AD17B` (required, UUID) - ID сессии
+ `usersInBatch`: 40 (required, number) - Количество пользователей на 360 градусов
+ `batches`: 2 (required, number) - Количество выборок.
Если количество пользователей 40 а batches = 2 то прийдет 2 массива по 40 пользователей
+ `currentLatitude`: 59.852806 (float) - Текущие координаты широты
+ `currentLongitude`: 30.42288 (float) - Текущие координаты долготы

В ответ приходит массив массивов объекта `target`. Количество вложенных массивов зависит от параметра `batches`.
Объект `target` имеет такие поля:
+ `userId` (UUID) - Идентификатор пользователя
+ `name` (string) - Имя пользователя
+ `birthday` (string) - День рождения пользователя в формате RFC 3339 ISO 8601
+ `ststus` (string) - Статус пользователя
    + `normal` - обычный пользователь
    + `invited` - пользователь которому мы отправили приглашение
    + `inviter` - пользователь отправивший приглашение нам
    + `appointment` - пользователь с которым у нас подтвержденная встреча
+ `appointmentId` (optional, UUID) - ID встречи
+ `photo` (dictionary) - Фото пользователя с разными размерами
    + `preview` (string) - URL квадратного фото размером 120х120
    + `previewMedium` (string) - URL квадратного фото размером 180х180
    + `previewLarge` (string) - URL квадратного фото размером 240х240
+ `location` (dictionary) - Месторасположение пользователя
    + `latitude` (float) - Широта
    + `longitude` (float) - Долгота

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "usersInBatch": 2,
            "batches": 2,
            "currentLatitude": 59.852806,
            "currentLongitude": 30.42288
        }

+ Response 200 (application/json)

        {
            "targets": [
                [
                    {
                        "userId": "2A4B2528-069B-11E5-879B-757BB664A5DC",
                        "name": "Кристина",
                        "birthday": "1989-3-3T00:00:00.00Z",
                        "status": "normal",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.882806,
                            "longitude": 30.45288
                        }
                    },
                    {
                        "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
                        "name": "Валерия",
                        "birthday": "1990-5-12T00:00:00.00Z",
                        "status": "invited",
                        "appointmentId": "7F76F4D2-06A0-11E5-82A6-01E861EA09BE",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.842806,
                            "longitude": 30.41288
                        }
                    }
                ],
                [
                    {
                        "userId": "5864AAC4-069B-11E5-9941-757BB664A5DC",
                        "name": "Светлана",
                        "birthday": "1986-12-4T00:00:00.00Z",
                        "status": "inviter",
                        "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.872806,
                            "longitude": 30.43288
                        }
                    },
                    {
                        "userId": "7405130E-069B-11E5-8882-757BB664A5DC",
                        "name": "Мария",
                        "birthday": "1993-5-3T00:00:00.00Z",
                        "status": "appointment",
                        "appointmentId": "63386058-06CD-11E5-AEE4-3C774B860EDE"
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.892806,
                            "longitude": 30.45288
                        }
                    }
                ]
            ]
        }

## Specific target [GET /targets/{userId}]

+ Parameters
    + userId (UUID) - ID пользователя

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B"
        }

+ Response 200 (application/json)

        {
            "target": {
                "userId": "7405130E-069B-11E5-8882-757BB664A5DC",
                "name": "Мария",
                "birthday": "1993-5-3T00:00:00.00Z",
                "status": "appointment",
                "appointmentId": "63386058-06CD-11E5-AEE4-3C774B860EDE"
                "photo": {
                    "preview": "http://preview.jpg",
                    "previewMedium": "http://previewMedium.jpg",
                    "previewLarge": "http://previewLarge.jpg"
                },
                "location": {
                    "latitude": 59.892806,
                    "longitude": 30.45288
                }
            }
        }


# Places [/places]

Метод получения мест встречи

## Places [GET]

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B"
        }

+ Response 200 (application/json)

        {
            "places": [
                {
                    "placeId": "544B3FD2-06C5-11E5-9762-D634EB8A2689",
                    "name": "A",
                    "location": {
                        "latitude": 59.802800,
                        "longitude": 30.39246
                    }
                },
                {
                    "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC",
                    "name": "B",
                    "location": {
                        "latitude": 59.801850,
                        "longitude": 30.39274
                    }
                },
                {
                    "placeId": "167C6846-06D1-11E5-AE66-BABBDD9DA696",
                    "name": "C",
                    "location": {
                        "latitude": 59.832842,
                        "longitude": 30.32237
                    }
                }
            ],
            "scale": {
                "diameter": 3548.02,
                "center": {
                    "latitude": 59.802800,
                    "longitude": 30.39278
                }
            }
        }

# Appointments [/appointments]

Группа методов для функционала «Давай встретимся»

## Get all appointments [GET]

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B"
        }

+ Response 200 (application/json)

        {
            "appointments": [
                {
                    "appointmentId": "63386058-06CD-11E5-AEE4-3C774B860EDE",
                    "status": "accepted",
                    "userId": "7405130E-069B-11E5-8882-757BB664A5DC",
                    "placeId": "167C6846-06D1-11E5-AE66-BABBDD9DA696"
                },
                {
                    "appointmentId": "7F76F4D2-06A0-11E5-82A6-01E861EA09BE",
                    "status": "made",
                    "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
                    "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
                },
                {
                    "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC",
                    "status": "accepted",
                    "userId": "5864AAC4-069B-11E5-9941-757BB664A5DC",
                    "placeId": "544B3FD2-06C5-11E5-9762-D634EB8A2689"
                }
            ]
        }

## Get specific appointment [GET /appointments/{appointmentId}]

+ Parameters
    + appointmentId (UUID) - ID нужной встречи

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B"
        }

+ Response 200 (application/json)

        {
            "appointment": {
                "appointmentId": "7F76F4D2-06A0-11E5-82A6-01E861EA09BE",
                "status": "made",
                "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
                "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
            }
        }

## Make an appointment [POST]

+ Request (application/json)

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
            "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
        }

+ Response 201 (application/json)

        {
            "appointment": {
                "appointmentId": "7F76F4D2-06A0-11E5-82A6-01E861EA09BE",
                "status": "made",
                "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
                "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
            }
        }

+ Response 403 (application/json)

        {
            "error": {
                "message": "Вы не можете назначить новую встречу, пока не закончили текущую",
                "description": "Чтобы назначить новую встречу, завершите текущую или отмените ее. Если вашу встречу отменила вторая сторона, вы снова сможете назначать встречи."
            }
        }

## Change appointment status [PUT]

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC",
            "status": "accepted"
        }

+ Response 200 (application/json)

        {
            "appointment": {
                "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC",
                "status": "accepted",
                "userId": "5864AAC4-069B-11E5-9941-757BB664A5DC",
                "placeId": "544B3FD2-06C5-11E5-9762-D634EB8A2689"
            }
        }

## Break an appointment [DELETE]

+ Request

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC"
        }
        
+ Response 204

