FORMAT: 1A
HOST: https://dev.api.privetapp.ru/ar/v1/

# PrivetAR

# Radar [/targets]

Метод отдает запрашиваемое количество людей в радиусе 360 градусов с равномерным распределением по градусам, и запасом для обновления.

При старте приложение делает запрос на этот метод. Последующие запросы делаются при нажатии на кнопку обновления.

## Targets [GET]

Параметры запроса:
+ `sessionId` : `653527D9-D4E8-43D7-A8C1-5B28C04AD17B` (required, UUID) - ID сессии
+ `usersInBatch`: 40 (required, number) - Количество пользователей на 360 градусов
+ `batches`: 2 (required, number) - Количество выборок.
Если количество пользователей 40 а batches = 2 то прийдет 2 массива по 40 пользователей
+ `currentLatitude`: 59.852806 (float) - Текущие координаты широты
+ `currentLongitude`: 30.42288 (float) - Текущие координаты долготы

В ответ приходит массив массивов объекта `target`. Количество вложенных массивов зависит от параметра `batches`.
Объект `target` имеет такие поля:
+ `userId` (UUID) - Идентификатор пользователя
+ `name` (string) - Имя пользователя
+ `birthday` (string) - День рождения пользователя в формате RFC 3339 ISO 8601
+ `ststus` (string) - Статус пользователя
    + `normal` - обычный пользователь
    + `invited` - пользователь которому мы отправили приглашение
    + `inviter` - пользователь отправивший приглашение нам
    + `appointment` - пользователь с которым у нас подтвержденная встреча
+ `photo` (dictionary) - Фото пользователя с разными размерами
    + `preview` (string) - URL квадратного фото размером 120х120
    + `previewMedium` (string) - URL квадратного фото размером 180х180
    + `previewLarge` (string) - URL квадратного фото размером 240х240
+ `location` (dictionary) - Месторасположение пользователя
    + `latitude` (float) - Широта
    + `longitude` (float) - Долгота

+ Request (application/json)

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "usersInBatch": 2,
            "batches": 2,
            "currentLatitude": 59.852806,
            "currentLongitude": 30.42288
        }

+ Response 200 (application/json)

        {
            "targets": [
                [
                    {
                        "userId": "2A4B2528-069B-11E5-879B-757BB664A5DC",
                        "name": "Кристина",
                        "birthday": "1989-3-3T00:00:00.00Z",
                        "status": "normal",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.882806,
                            "longitude": 30.45288
                        }
                    },
                    {
                        "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
                        "name": "Валерия",
                        "birthday": "1990-5-12T00:00:00.00Z",
                        "status": "invited",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.842806,
                            "longitude": 30.41288
                        }
                    }
                ],
                [
                    {
                        "userId": "5864AAC4-069B-11E5-9941-757BB664A5DC",
                        "name": "Светлана",
                        "birthday": "1986-12-4T00:00:00.00Z",
                        "status": "inviter",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.872806,
                            "longitude": 30.43288
                        }
                    },
                    {
                        "userId": "7405130E-069B-11E5-8882-757BB664A5DC",
                        "name": "Мария",
                        "birthday": "1993-5-3T00:00:00.00Z",
                        "status": "appointment",
                        "photo": {
                            "preview": "http://preview.jpg",
                            "previewMedium": "http://previewMedium.jpg",
                            "previewLarge": "http://previewLarge.jpg"
                        },
                        "location": {
                            "latitude": 59.892806,
                            "longitude": 30.45288
                        }
                    }
                ]
            ]
        }

# Appointments [/appointments]

Группа методов для функционала «Давай встретимся»

## Make an appointment [POST]

+ Request (application/json)

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
            "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
        }

+ Response 201 (application/json)

        {
            "appointment": {
                "appointmentId": "7F76F4D2-06A0-11E5-82A6-01E861EA09BE",
                "status": "made",
                "target": {
                    "userId": "463EC690-069B-11E5-88C0-757BB664A5DC",
                    "name": "Валерия",
                    "birthday": "1990-5-12T00:00:00.00Z",
                    "status": "invited",
                    "photo": {
                        "preview": "http://preview.jpg",
                        "previewMedium": "http://previewMedium.jpg",
                        "previewLarge": "http://previewLarge.jpg"
                    },
                    "location": {
                        "latitude": 59.842806,
                        "longitude": 30.41288
                    }
                },
                "place": {
                    "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
                }
            }
        }

+ Response 403 (application/json)

        {
            "error": {
                "message": "Вы не можете назначить новую встречу, пока не закончили текущую",
                "description": "Чтобы назначить новую встречу, завершите текущую или отмените ее. Если вашу встречу отменила вторая сторона, вы снова сможете назначать встречи."
            }
        }

## Change appointment status [PUT]

+ Request (application/json)

        {
            "sessionId": "653527D9-D4E8-43D7-A8C1-5B28C04AD17B",
            "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC",
            "status": "accepted"
        }

+ Response 200 (application/json)

        {
            "appointment": {
                "appointmentId": "2B64F850-06A8-11E5-879B-757BB664A5DC",
                "status": "accepted",
                "target": {
                    "userId": "5864AAC4-069B-11E5-9941-757BB664A5DC",
                    "name": "Светлана",
                    "birthday": "1986-12-4T00:00:00.00Z",
                    "status": "appointment",
                    "photo": {
                        "preview": "http://preview.jpg",
                        "previewMedium": "http://previewMedium.jpg",
                        "previewLarge": "http://previewLarge.jpg"
                    },
                    "location": {
                        "latitude": 59.872806,
                        "longitude": 30.43288
                    }
                },
                "place": {
                    "placeId": "90E0E65E-069D-11E5-8882-757BB664A5DC"
                }
            }
        }
